# Generated by Django 4.2.3 on 2023-09-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0006_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangobackend.tour'),
        ),
    ]
